# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation


apiVersion: apps/v1
kind: Pod
metadata:
  name: flowconfig-daemon
  namespace: system
spec:
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  # ddp package directory is needed by the dpdk ice driver
  - name: iceddp
    hostPath:
      path: /var/lib/firmware/intel/ice/ddp
