# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    control-plane: flowconfig-daemon
  name: flowconfig-daemon
  namespace: intel-ethernet-operator-system
spec:
  containers:
  - args:
    - /entrypoint.sh
    command:
    - /bin/bash
    - -c
    - --
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: PYTHONIOENCODING
      value: UTF-8
    image: dcf-tool:v21.08
    name: uft
    resources:
      limits:
        hugepages-2Mi: 2Gi
        memory: 200Mi
      requests:
        hugepages-2Mi: 2Gi
        memory: 200Mi
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - IPC_LOCK
        - SYS_NICE
      privileged: true
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    - mountPath: /lib/firmware/intel/ice/ddp
      name: iceddp
      readOnly: true
  - command:
    - /flowconfig-daemon
    env:
    - name: OPERATOR_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    image: intel-ethernet-operator-flowconfig-daemon:0.0.1
    name: flowconfig-daemon
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 20Mi
  serviceAccountName: intel-ethernet-operator-controller-manager
  terminationGracePeriodSeconds: 10
  volumes:
  - emptyDir:
      medium: HugePages
    name: hugepage
  - hostPath:
      path: /var/lib/firmware/intel/ice/ddp
    name: iceddp
